import * as translateApi from '@/_services';
import { ToastCtx } from '@/content/_toast';
import { useEffect } from 'react';

type StatefulData = ['pending', { i: string }] | ['resolved', { i: string; o: string }];

function useTranslate() {
    const { add, close, update } = ToastCtx.useToastManager();

    return translate;
    function translate(i: string) {
        const id = crypto.randomUUID();
        const abortController = new AbortController();
        const cancel = () => (close(id), abortController.abort());

        add<StatefulData>({ id, data: ['pending', { i }] });

        (async () => {
            await sleep();
            const [isOk, o] = await translateApi.chrome(i, {
                sourceLang: 'en',
                targetLang: 'zh',
                signal: abortController.signal,
            });

            if (!isOk) return;
            if (abortController.signal.aborted) return;

            update<StatefulData>(id, { data: ['resolved', { i, o }] });
        })();

        return cancel;
    }
}

function useTrigger(action: (i: string) => void) {
    // @todo Cleanup effect generated by action.
    useEffect(() => {
        document.addEventListener('keydown', onKeydown, { capture: true });
        return () => document.removeEventListener('keydown', onKeydown, { capture: true });

        function onKeydown(ev: KeyboardEvent) {
            if (ev.key.toLowerCase() !== 'f3') return;

            const selection = getSelection();
            if (!selection) return;

            const str = selection.toString().trim();
            if (str === '') return;

            action(str);
        }
    }, [action]);
}

async function sleep() {
    return new Promise<undefined>((resolve) => {
        setTimeout(() => resolve(undefined), 1500);
    });
}

export { useTranslate, useTrigger };
export type { StatefulData };
